version: "3.2"
services:
   nginx:
       container_name: nginx
       image: nginx:1.17.8
       ports:
           - 80:80
       volumes:
           - ./config/nginx/site.conf:/etc/nginx/conf.d/site.conf
           - ./php_app:/php_app
       links:
           - php_app
           - node_app
   php_app:
       build: php_app
       container_name: php_app
       volumes:
           - ./php_app:/php_app
       environment:  
           - SESSION_HANDLER=redis
           - SESSION_PATH=tcp://redis:${REDIS_PORT}?auth=${REDIS_PASSWORD}  
           - SESSION_MAX_TIME_LIFE=86400
   node_app:
        build: node_app
        container_name: node_app
        volumes: 
            - ./node_app:/node_app
   redis:
        image: redis:4-alpine
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}